export const FETCH_CAMPAIGN = 'FETCH_CAMPAIGN';
export const FETCH_CAMPAIGN_FAILED = 'FETCH_CAMPAIGN_FAILED';
export const FETCH_CAMPAIGN_SUCCEEDED = 'FETCH_CAMPAIGN_SUCCEEDED';
export const UPDATE_EDITING_CAMPAIGN = 'UPDATE_EDITING_CAMPAIGN';

export const FETCH_CAMPAIGNS = 'FETCH_CAMPAIGNS';
export const FETCH_CAMPAIGNS_FAILED = 'FETCH_CAMPAIGNS_FAILED';
export const FETCH_CAMPAIGNS_SUCCEEDED = 'FETCH_CAMPAIGNS_SUCCEEDED';

export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
export const CREATE_CAMPAIGN_FAILED = 'CREATE_CAMPAIGN_FAILED';
export const CREATE_CAMPAIGN_SUCCEEDED = 'CREATE_CAMPAIGN_SUCCEEDED';

export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN';
export const UPDATE_CAMPAIGN_DONE = 'UPDATE_CAMPAIGN_DONE';

export const SHOW_CAMPAIGN_CREATION_MODAL = 'SHOW_CAMPAIGN_CREATION_MODAL';
export const HIDE_CAMPAIGN_CREATION_MODAL = 'HIDE_CAMPAIGN_CREATION_MODAL';

export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const DELETE_CAMPAIGN_SUCCEEDED = 'DELETE_CAMPAIGN_SUCCEEDED';
