export const FETCH_UPLOADED_MOVIES = 'FETCH_UPLOADED_MOVIES';
export const FETCH_UPLOADED_MOVIES_FAILED = 'FETCH_UPLOADED_MOVIES_FAILED';
export const FETCH_UPLOADED_MOVIES_SUCCEEDED = 'FETCH_UPLOADED_MOVIES_SUCCEEDED';
