version: '3'
services:
  front:
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app

networks:
  default:
    external: true
    name: lecourt
