export const UPLOAD_MOVIE = 'UPLOAD_MOVIE';
export const UPLOAD_MOVIE_SUCCEEDED = 'UPLOAD_MOVIE_SUCCEEDED';
export const UPLOAD_MOVIE_FAILED = 'UPLOAD_MOVIE_FAILED';

export const UPLOAD_MOVIE_FILE_SUCCEEDED = 'UPLOAD_MOVIE_FILE_SUCCEEDED';
export const UPLOAD_MOVIE_FILE_FAILED = 'UPLOAD_MOVIE_FILE_FAILED';

export const FETCH_PERSONS = 'FETCH_PERSONS';
export const FETCH_PERSONS_SUCCEEDED = 'FETCH_PERSONS_SUCCEEDED';
export const FETCH_PERSONS_FAILED = 'FETCH_PERSONS_FAILED';
