export const FETCH_MOVIE_CREATION_DATA = 'FETCH_MOVIE_CREATION_DATA';

export const UPLOAD_MOVIE = 'UPLOAD_MOVIE';
export const UPLOAD_MOVIE_SUCCEEDED = 'UPLOAD_MOVIE_SUCCEEDED';
export const UPLOAD_MOVIE_FAILED = 'UPLOAD_MOVIE_FAILED';

export const UPLOAD_MOVIE_FILE_SUCCEEDED = 'UPLOAD_MOVIE_FILE_SUCCEEDED';
export const UPLOAD_MOVIE_FILE_FAILED = 'UPLOAD_MOVIE_FILE_FAILED';

export const SHOW_UPLOAD_MOVIE_MODAL = 'SHOW_UPLOAD_MOVIE_MODAL';
export const HIDE_UPLOAD_MOVIE_MODAL = 'HIDE_UPLOAD_MOVIE_MODAL';
