export const UPLOAD_MOVIE = 'UPLOAD_MOVIE';
export const UPLOAD_MOVIE_SUCCEEDED = 'UPLOAD_MOVIE_SUCCEEDED';
export const UPLOAD_MOVIE_FAILED = 'UPLOAD_MOVIE_FAILED';

export const UPLOAD_MOVIE_FILE_SUCCEEDED = 'UPLOAD_MOVIE_FILE_SUCCEEDED';
export const UPLOAD_MOVIE_FILE_FAILED = 'UPLOAD_MOVIE_FILE_FAILED';