export const DELETE_ENTITY = 'DELETE_ENTITY';
export const DELETE_ENTITY_SUCCEEDED = 'DELETE_ENTITY_SUCCEEDED';
export const DELETE_ENTITY_FAILED = 'DELETE_ENTITY_FAILED';

export const SET_EDIT_ENTITY = 'SET_EDIT_ENTITY';
export const EDIT_ENTITY = 'EDIT_ENTITY';
export const EDIT_ENTITY_SUCCEEDED = 'EDIT_ENTITY_SUCCEEDED';

export const CREATE_ENTITY = 'CREATE_ENTITY';
export const CREATE_ENTITY_SUCCEEDED = 'CREATE_ENTITY_SUCCEEDED';
export const CREATE_ENTITY_FAILED = 'CREATE_ENTITY_FAILED';
