export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_SUCCEEDED = 'FETCH_COUNTRIES_SUCCEEDED';
export const FETCH_COUNTRIES_FAILED = 'FETCH_COUNTRIES_FAILED';

export const FETCH_PERSONS = 'FETCH_PERSONS';
export const FETCH_PERSONS_SUCCEEDED = 'FETCH_PERSONS_SUCCEEDED';
export const FETCH_PERSONS_FAILED = 'FETCH_PERSONS_FAILED';

export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_GENRES_SUCCEEDED = 'FETCH_GENRES_SUCCEEDED';
export const FETCH_GENRES_FAILED = 'FETCH_GENRES_FAILED';

export const FETCH_USER_INIT_APP = 'FETCH_USER_INIT_APP';
export const FETCH_USER_INIT_APP_SUCCEEDED = 'FETCH_USER_INIT_APP_SUCCEEDED';
export const FETCH_USER_INIT_APP_FAILED = 'FETCH_USER_INIT_APP_FAILED';
