export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_TOKEN_SUCCEEDED = 'FETCH_TOKEN_SUCCEEDED';
export const FETCH_TOKEN_FAILED = 'FETCH_TOKEN_FAILED';
export const RESTORE_TOKEN = 'RESTORE_TOKEN';
export const LOGOUT = 'LOGOUT';
