export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_DETAILS_SUCCEEDED = 'FETCH_MOVIE_DETAILS_SUCCEEDED';
export const FETCH_MOVIE_DETAILS_FAILED = 'FETCH_MOVIE_DETAILS_FAILED';
